driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: freebsd-10.3
  - name: freebsd-11.0
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: sles-12-sp1
    driver:
      box: chef/sles-12-sp1-x86_64 # private box
  - name: solaris-10.11
    driver:
      box: chef/solaris-10.11 # private box
  - name: solaris-11.3
    driver:
      box: chef/solaris-11.3 # private box
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: default
  run_list:
  - recipe[cron_test::default]
