name              'cron'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs cron'
version           '7.0.8'
source_url        'https://github.com/sous-chefs/cron'
issues_url        'https://github.com/sous-chefs/cron/issues'
chef_version      '>= 12.15'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'omnios'
supports 'opensuse'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'smartos'
supports 'solaris2'
supports 'suse'
supports 'ubuntu'
supports 'zlinux'
